apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      retention: 7d
      volumeClaimTemplate:
        spec:
          storageClassName: local-storageclass
          volumeMode: Filesystem
          resources:
            requests:
              storage: 25Gi
