apiVersion: v1
baseDomain: example2.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp4
networking:
  clusterNetworks:
  - cidr: 10.254.0.0/16
    hostPrefix: 24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '{"auths": ...}'
sshKey: 'ssh-ed25519 AAAA...'
additionalTrustBundle: |                                                                                                                                                                                           
  -----BEGIN CERTIFICATE-----
  <insert your cert here>
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - <your-mirror-registry>:<port>/ocp-release
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - <your-mirror-registry>:<port>/ocp-release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - <your-mirror-registry>:<port>/ocp-release
  source: registry.svc.ci.openshift.org/ocp/release

